### ISSUE TITLE
How to set up BIOS?

### ISSUE THREAD

**Issue by astonishsn** [rchiruma/SurfaceLaptop3-OpenCore#1]
Hello, I do not know what BIOS should do the corresponding Settings,Can you tell me more about how to set up BIOS ? One more small question, is there any progress on sleep?

**Comment by rchiruma** [comment]
I did not change much in the bios other than disabling secure boot. Surface Laptop does not have many options in BIOS/UEFI.

I could not get sleep to work so far. It appears that Surface devices do not implement S3. Makes it very hard to get sleep working

**Comment by astonishsn** [comment]
I found the surface pro 7 to install Monterey's EFI and according to the creator the sleep is normal.  [](url)
